### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by chfast** [chfast/ethash#2]
- [x] Add README file.
- [x] Cross-compile for mips64.
- [x] Add support for big-endian.
- [x] Add CI.
- [x] Add code coverage.
- [x] Build with asserts.
- [x] CMake: add install.
- [x] CMake: export config.
- [ ] Switch to C only API.
- [ ] Add C++ wrapper for C API.
- [x] Add 32-bit builds (Windows, linux?)
- [x] Test with sanitizers on CIs
- [x] Switch to UBSan from clang.
- [x] Export keccack.
- [x] Add PowerPC build.
- [x] Extend UBSan build with clang 6.
- [x] Build with PGO.
